### PR TITLE
Slicing, sorting and dropping index/column values

### LINKED ISSUE #19: Reordering values in view results
We need a way to reorder values in the result of views.

For example, given the following view:

```python
Question            gender  
Values              @
Question    Values  
q1          1       7.201447
            2       9.64925
            3       55.662665
            4       72.663656
            5       4.704566
            6       11.496034
            7       21.69883
            8       3.178551
            9       0.099151
            96      2.199429
            98      2.497416
            99      8.949005
```

We need a way to specify a new values order in the index. For example, in this case the values 1-9 have been reversed.

```python
Question            gender       
Values              @
Question    Values  
q1          9       0.099151
            8       3.178551
            7       21.69883
            6       11.496034
            5       4.704566
            4       72.663656
            3       55.662665
            2       9.64925
            1       7.201447
            96      2.199429
            98      2.497416
            99      8.949005
```

I'll implement this using column meta tags that are picked up by paint_dataframe.

### PR DESCRIPTION
**Pull request by jamesrkg**
This branch resolves #19, #15 and #18.

### CODE REVIEW

**Comment by jamesrkg** [comment]
Pushing the deadline on this PR back a week to allow for more testing.

**Comment by jamesrkg** [comment]
Quite a bit of refactoring to do on this so I'm giving it another week.

**Comment by alextanski** [comment]
:+1:

**Comment by jamesrkg** [comment]
I'll continue adding tests and making improvements in a new branch. For now this is sufficiently functional to warrant a merge to develop. :+1:

**Pull request merged**
