### PR TITLE
Weight groups fix v2

### PR DESCRIPTION
**Pull request by jamesrkg**
This is a clone of a previous PR that was targeted master, but should have targeted develop.

Original PR submitted by @alextanski 

This is the first part of the cleanup of the Weight module.

- Added support for complex filters (passed into the DataFrame.query() method).
- Bugfixing related to issues that Alasadair reported while setting up the omni template.
- Removed some obsolote methods
- Modularized a lot (for example: basic weight factor computation, group weights and total scaling are now separate methods)
- Adjusted and added some unit tests.
- Added API reference for the cleaned Rim class into the docs. These are rendered as well.

### CODE REVIEW

**Comment by jamesrkg** [comment]
I'm shifting this to RG-2, because there's something I want to add to the branch.

**Comment by jamesrkg** [comment]
I've updated the way the user access the weight report summaries of an engine. This new method calculates all of the metrics (except iterations) on the fly and so is more stable than the previous method (which will be deprecated with a subsequent commit).

New usage example:

```python
>>> engine.get_report()


Weight variable            weights_A    weights_B    weights_C    weights_D    weights_E                                                    
Weight group          _default_name_          all          all           W1           W1           W2           W3           W4           W5
Weight filter                   None         None         None      Wave==1      Wave==1      Wave==2      Wave==3      Wave==4      Wave==5
Total: unweighted        8078.000000  8078.000000  8078.000000  1577.000000  1577.000000  1631.000000  1652.000000  1607.000000  1611.000000
Total: weighted          8078.000000  8078.000000  2000.000000  1577.000000  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
Weighting efficiency       50.978811    50.978811    50.978811    50.964163    50.964163    49.494006    52.656787    51.030417    49.951275
Iterations required         9.000000     9.000000     9.000000    12.000000    12.000000    14.000000    11.000000    10.000000    10.000000
Minimum weight factor       0.255351     0.255351     0.063221     0.262189     0.166258     0.157363     0.156769     0.149134     0.158837
Maximum weight factor       2.968669     2.968669     0.735001     2.943747     1.866676     1.993634     1.744400     1.951616     1.927773
Weight factor ratio        11.625826    11.625826    11.625826    11.227557    11.227557    12.668975    11.127188    13.086321    12.136803
```

**Comment by AlasdairE** [comment]
:+1:

**Comment by jamesrkg** [comment]
:+1:

**Pull request merged**
