### PR TITLE
Improved error message for when a view that does not exist in the sta…

### PR DESCRIPTION
**Pull request by AlasdairE**
…ck has been added to the chains. Now it will print the view, data key, filter key, x key and y key to help the user identify the source of the missing view.

### CODE REVIEW

**Comment by AlasdairE** [comment]
Here is an example:

```python
Exception                                 Traceback (most recent call last)
<ipython-input-10-361d370ed80f> in <module>()
     16         },
     17         display_names=['x'],
---> 18         create_toc=True
     19     )
     20     print '{}.xlsx'.format(os.path.basename(path_excel))

C:\Anaconda\lib\site-packages\quantipy\core\builds\excel\excel_painter.py in ExcelPainter(path_excel, meta, cluster, grouped_views, text_key, annotations, display_names, create_toc)
   1123                                         fk=chain.filter,
   1124                                         xk=x,
-> 1125                                         yk=y
   1126                                     )
   1127                                 )

Exception: 
A view in the chains, x|frequency|x:y|||cbase, does not exist in the stack for...
data_key=OM_2015_290_Compiler_London_G4_edited
filter=(age >= 18)
x=weights_LONDON18
y=lnews
```

**Comment by jamesrkg** [comment]
Praise the lord!

**Comment by AlasdairE** [comment]
:+1:

**Comment by jamesrkg** [comment]
:+1:

**Pull request merged**
